version: '3.8'

services:
    payment-service:
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
         - "6000:6000"
      environment:
          DATABASE_URL: ${DATABASE_URL}
      command: npm run dev
      depends_on:
          - payment-db

    payment-db:
      image: postgres:14
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5434:5432"  # Host port 5434 -> Container port 5432 (PostgreSQL default)
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
