services:
  payment-service:
    container_name: payment-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      payment-db:
        condition: service_healthy

  payment-db:
    container_name: payment-db
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"  
    volumes:
      - payment-service_postgres-data:/var/lib/postgresql/data  # Correct volume name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  payment-service_postgres-data: {}  
