apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: payment-service
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL2JpbmFtaW46YmluYW1pbkBwYXltZW50LWRiOjU0MzIvcGF5bWVudHNlcnZpY2U/c2NoZW1hPXB1YmxpYw==
  user: YmluYW1pbg==
  password: YmluYW1pbg==
  database: cGF5bWVudHNlcnZpY2U=