
services:
    notification-service:
      container_name: notification-service
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
         - "8000:8000"
      environment:
          DATABASE_URL: ${DATABASE_URL}
      depends_on:
          - notification-db

    notification-db:
      image: postgres:14
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5436:5432" # Host port 5436 -> Container port 5432 (PostgreSQL default)
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
