apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-blue
  namespace: notification-service
  labels:
    app: notification-service
    environment: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      environment: blue
  template:
    metadata:
      labels:
        app: notification-service
        environment: blue
    spec:
      containers:
      - name: notification-service
        image: binamin/notification-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: url
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "256Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
     