
services:
    cart-service:
      container_name: cart-service
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
         - "7000:7000"
      environment:
          DATABASE_URL: ${DATABASE_URL}
      depends_on:
          - cart-db
      networks:
          - ecommerceNetwork

    cart-db:
      image: postgres:14
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5437:5432" 
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
          - ecommerceNetwork 


volumes:
  postgres-data: {}

networks:
    ecommerceNetwork:
        external: true
