version: '3.8'

services:
    cart-service:
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
         - "7000:7000"
      environment:
          DATABASE_URL: ${DATABASE_URL}
      depends_on:
          - cart-db

    cart-db:
      image: postgres:14
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5437:5432" # Host port 5437 -> Container port 5432 (PostgreSQL default)
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
