version: '3.8'

services:
    order-service:
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
         - "5005:5005"
      environment:
          DATABASE_URL: ${DATABASE_URL}
      depends_on:
          - order-db

    order-db:
      image: postgres:14
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5435:5432" # Host port 5435 -> Container port 5432 (PostgreSQL default)
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
