apiVersion: apps/v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL2JpbmFtaW46YmluYW1pbkBvcmRlci1kYjo1NDMyL29yZGVyc2VydmljZT9zY2hlbWE9cHVibGljCg==
  user: YmluYW1pbg==
  password: YmluYW1pbg==
  database: b3JkZXJzZXJ2aWNl