name: Ecommerce Pipeline

on:
  push:
    paths:
      - 'services/**'
  pull_request:
    paths:
      - 'services/**'

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - notification-service
          - cart-service
          - payment-service
          - product-service
          
    steps:
      # check out the code
      - name: checkout code
        uses: actions/checkout@v3

      # Set up node.js
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      # install dependencies
      - name: Install dependencies
        working-directory: services/${{matrix.service}}
        run: npm install

      # Run test
      - name: Run tests
        working-directory: services/${{matrix.service}}
        run: npm test

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        working-directory: services/{{matrix.service}}
        run: |
          docker build -t $DOCKER_USERNAME/${{ matrix.service }}:${{ github.sha }} .
          docker push $DOCKER_USERNAME/${{ matrix.service }}:${{ github.sha }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        working-directory: services/${{matrix.service}}
        run: |



